import { $, $$ } from "../selectors/selectors";

export const avaliationInput = $("#avaliation");
export const avaliationValue = $("#avaliationValue");
export const endYear = $("#endYear");
export const keyword = $("#keyword");
export const modal = $("#movie-modal");
export const moviesContainer = $("#movies");
export const modalContent = $("#modal-content");
export const paginationContainer = $("#pagination");
export const ratingInput = $("#rating");
export const ratingValue = $("#ratingValue");
export const inputSearch = $("#input-search");
export const startYear = $("#startYear");
export const skeletonCard = $$(".skeleton-card");
export const sentinel = $("#sentinel");
export const suggestions = $("#suggestions");
export const spinner = $("#spinner");
export const btnFilter = $("#btn-filter");
export const btnFilterSpinner = $(".btn-filter-spinner");
export const btnFilterText = $(".btn-filter-text");
export const btnSearch = $("#btn-search");
export const btnSearchSpinner = $(".btn-search-spinner");
export const btnSearchText = $(".btn-search-text");
export const sortSelect = $("#sortSelect");
export const genreList = $("#with-genres");
export const language = $("#language");