export const sortOptions = [
  ["", "Ordenar por"],
  ["popularity.desc", "Popularidade (↓)"],
  ["popularity.asc", "Popularidade (↑)"],
  ["release_date.desc", "Data de Lançamento (↓)"],
  ["release_date.asc", "Data de Lançamento (↑)"],
  ["vote_average.desc", "Avaliação (↓)"],
  ["vote_average.asc", "Avaliação (↑)"],
  ["title.asc", "Título [A-Z]"],
  ["title.desc", "Título [Z-A]"],
];

export const genres = [
  { id: 28, name: "Ação" },
  { id: 12, name: "Aventura" },
  { id: 16, name: "Animação" },
  { id: 10770, name: "Cinema TV" },
  { id: 35, name: "Comédia" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentário" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Família" },
  { id: 37, name: "Faroeste" },
  { id: 14, name: "Fantasia" },
  { id: 878, name: "Ficção científica" },
  { id: 10752, name: "Guerra" },
  { id: 36, name: "História" },
  { id: 10402, name: "Música" },
  { id: 9648, name: "Mistério" },
  { id: 10749, name: "Romance" },
  { id: 27, name: "Terror" },
  { id: 53, name: "Thriller" },
];

export const languages = [
  { iso_639_1: "", name: "Todos" },
  { iso_639_1: "pt", name: "Português" },
  { iso_639_1: "en", name: "Inglês" },
  { iso_639_1: "es", name: "Espanhol" },
  { iso_639_1: "fr", name: "Francês" },
  { iso_639_1: "de", name: "Alemão" },
  { iso_639_1: "it", name: "Italiano" },
  { iso_639_1: "ja", name: "Japonês" },
  { iso_639_1: "ko", name: "Coreano" },
  { iso_639_1: "zh", name: "Chinês" },
  { iso_639_1: "ru", name: "Russo" },
  { iso_639_1: "hi", name: "Hindi" },
  { iso_639_1: "ar", name: "Árabe" },
  { iso_639_1: "tr", name: "Turco" },
  { iso_639_1: "pl", name: "Polonês" },
  { iso_639_1: "nl", name: "Holandês" },
  { iso_639_1: "sv", name: "Sueco" },
  { iso_639_1: "fi", name: "Finlandês" },
  { iso_639_1: "no", name: "Norueguês" },
  { iso_639_1: "da", name: "Dinamarquês" },
  { iso_639_1: "he", name: "Hebraico" },
  { iso_639_1: "el", name: "Grego" },
  { iso_639_1: "th", name: "Tailandês" },
  { iso_639_1: "cs", name: "Tcheco" },
  { iso_639_1: "ro", name: "Romeno" },
  { iso_639_1: "hu", name: "Húngaro" },
  { iso_639_1: "vi", name: "Vietnamita" },
  { iso_639_1: "uk", name: "Ucraniano" },
  { iso_639_1: "id", name: "Indonésio" },
  { iso_639_1: "ms", name: "Malaio" },
  { iso_639_1: "fa", name: "Persa" },
  { iso_639_1: "bn", name: "Bengali" },
  { iso_639_1: "ta", name: "Tâmil" },
  { iso_639_1: "te", name: "Telugo" },
];
